### ISSUE TITLE
Adding a pendulum environment/experiment

### ISSUE THREAD

**Issue by alexminnaar** [deepmind/bsuite#9]
I wanted to propose adding a pendulum experiment to bsuite.  I think it fits the targeted, simple, challenging, scalable, fast criteria outlined in the bsuite paper.  Also, now that https://github.com/deepmind/bsuite/pull/8 has been merged, ```DMEnvFromGym``` can be used to convert the [Openai pendulum environment](https://gym.openai.com/envs/Pendulum-v0/) to a bsuite environment without having to reimplement it i.e. something like

```
env = DMEnvFromGym(gym.make('Pendulum-v0'))
``` 

If there is interest I would be happy to work on it.  Also, let me know if there are any concerns with implementing homegrown environments vs importing them from third parties like Openai.

**Comment by iosband** [comment]
Hi Alex,

I agree that adding the pendulum environment is not going to be difficult techincally.

In order to make a good bsuite experiment though we need to think about what aspects of core RL behaviours this is trying to test, what the evaluation criteria are, and whether it adds significant value.

We are planning our next review of the bsuite for the NeurIPS 2019 Deep RL workshop - maybe you could put together a proposal in time for that, and either link it here or send it to bsuite.committee@gmail.com

Cheers,
Ian
